default_language_version:
  python: python3.12
exclude: ^(docs|\.venv|\.vscode)/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Upgrade syntax to newer versions of Python
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        description: "Upgrade syntax to newer versions"
        args: [--py310-plus, --keep-runtime-typing]

  # Ruff Python linter and formatter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.14.3"
    hooks:
      - id: ruff-format
        description: "Ruff Python formatter"
        types_or: [python, pyi, jupyter]
      - id: ruff
        description: "Ruff Python linter"
        args: ["--fix", "--config=./ruff.toml"]
        types_or: [python, pyi, jupyter]

  # Spelling checker
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        description: "Check for common misspellings"
        files: ^.*\.(py|c|h|md|rst|ya?ml)$
        additional_dependencies:
          - tomli

  # Python static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        description: "mypy static type checker"
        args: [--config-file=./mypy.ini, --install-types, --non-interactive]
        additional_dependencies: ["types-PyYAML"]

  # Find unused code in Python projects.
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        description: "Find unused code"
        args: [--min-confidence=80, src/]

  # Scan your uv.lock file for dependencies with known vulnerabilities.
  - repo: https://github.com/owenlamont/uv-secure
    rev: 0.14.4
    hooks:
      - id: uv-secure
        description: "Scan uv.lock for dependencies with known vulnerabilities"

  # Detect secrets in your codebase
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        description: "Prevent secrets from being committed"
        args:
          [
            "--baseline",
            ".secrets.baseline",
            "--exclude-lines",
            "(.*)# scan:ignore",
          ]
        exclude: package.lock.json

  # Detect common security issues in Python code.
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        description: "Detect common security issues"
        exclude: ^tests/
        args: [-r, src]

  # Static analysis tool for shell scripts.
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        name: Check Shell Scripts
        description: "Shell script linter"
        args: ["--severity=warning"]
        types_or: [shell, sh]
